//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MgJava2014.Models.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int userId { get; set; }
        public int stars { get; set; }
        public int points { get; set; }
    
        public virtual User User { get; set; }
    }
}
